#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend chris-domain.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 151902-web-01 54.209.99.124
        server 151902-web-02 18.215.160.108
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
