#!/usr/bin/env bash
# This Script connects to the server 54.209.99.124 using the users private key
# stored in a file school Found in the users home directory

ssh ubuntu@54.209.99.124 -i ~/.ssh/id_rsa
